DROP TABLE IF EXISTS Player CASCADE ;
DROP TABLE IF EXISTS Organiser CASCADE ;
DROP TABLE IF EXISTS Play_Table CASCADE ;
DROP TABLE IF EXISTS char_reg_table CASCADE ;
DROP TABLE IF EXISTS Character_ CASCADE ;
DROP TABLE IF EXISTS Scenario CASCADE ;